[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Landify"
authors = [{name = "SystemRaise Tecnologia LTDA", email = "contato@systemraise.com"}]
dynamic = ["version", "description"]
